name: Details on Issue
on:
  issues:
    types: [opened, edited, milestoned]
jobs:
  show-details:
    runs-on: ubuntu-latest
    steps:
      - name: "Show event detail"
        run: echo "${{toJSON(github.event)}}"
